apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-demo-pvc
  namespace: nginx-ns

spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
      
    