apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devboard
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/Gaur171188/DevboardPractiseDevOPS.git
    targetRevision: main
    path: helm/devboard

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: devboard-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true